### ISSUE TITLE
DNS Load Balancing

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#82]

**Comment by montyanderson** [comment]
The DNS currently points to our two servers:

```
$ dig yacdn.org

; <<>> DiG 9.11.3-1ubuntu1.5-Ubuntu <<>> yacdn.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24110
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;yacdn.org.			IN	A

;; ANSWER SECTION:
yacdn.org.		0	IN	A	51.15.124.253
yacdn.org.		0	IN	A	51.15.127.202

;; Query time: 35 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Apr 25 12:21:29 BST 2019
;; MSG SIZE  rcvd: 70
```

**Comment by montyanderson** [comment]
We can test both servers using curl's `--resolve`.

```
$ curl https://yacdn.org/proxy/https://gist.githubusercontent.com/montyanderson/2a07b9ae6a24811720a8fc1d7d3eb20c/raw/d594d6d329717378f5d6abc84897b061f6f/five-byte-file.txt --resolve "yacdn.org:51.15.124.253"
12345
```

```
$ curl https://yacdn.org/proxy/https://gist.githubusercontent.com/montyanderson/2a07b9ae6a24811720a8fc1d7d3eb20c/raw/d594d6d329717378f5d6abc84897b061f6f/five-byte-file.txt --resolve "yacdn.org:51.15.127.202"
12345
```

**Comment by super3** [comment]
On the main YaCDN server it seems to be complaining a bunch about Redis:

```
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
0|server   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|server   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
```
